version: 2

before:
  hooks:
    - go mod tidy
    # Build the embedded UI before compiling Go binaries
    - bash -c 'cd ui && pnpm install --frozen-lockfile && pnpm build'
    - bash -c 'rm -rf internal/web/dist && mkdir -p internal/web/dist && cp -r ui/packages/web-app/dist/* internal/web/dist/'

builds:
  - id: thrum
    binary: thrum
    main: ./cmd/thrum
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.Build={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: thrum
    formats:
      - tar.gz
    name_template: "thrum_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: leonletto
    name: thrum

# Homebrew cask (modern approach for precompiled binaries, GoReleaser v2.10+)
homebrew_casks:
  - repository:
      owner: leonletto
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/leonletto/thrum"
    description: "Git-backed agent messaging and coordination CLI"
    license: "MIT"
    commit_author:
      name: goreleaser
      email: goreleaser@leonletto.github.io
