#!/bin/bash
# Universal Thrum agent startup script
# Auto-generated by thrum init
set -e

# Bind Thrum to this checkout even if the agent later cds into another worktree.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_THRUM_HOME="$(cd "$SCRIPT_DIR/.." && pwd)"
export THRUM_HOME="${THRUM_HOME:-$DEFAULT_THRUM_HOME}"

# --- Listener heartbeat mode ---
# Usage: thrum-startup.sh --listener-heartbeat
# Updates the listener heartbeat in the agent's identity file.
# Requires THRUM_NAME and THRUM_AGENT_ID to be set (from CLAUDE_ENV_FILE).
if [ "$1" = "--listener-heartbeat" ]; then
  AGENT_ID="${THRUM_AGENT_ID:-${THRUM_NAME:-}}"
  if [ -z "$AGENT_ID" ]; then
    AGENT_ID=$(thrum --repo "$THRUM_HOME" whoami --json 2>/dev/null | jq -r 'select(.agent_id != null) | .agent_id // empty')
  fi
  if [ -z "$AGENT_ID" ]; then
    echo "Error: Could not determine agent ID" >&2
    exit 1
  fi

  IDENT_FILE="$THRUM_HOME/.thrum/identities/${AGENT_ID}.json"
  if [ ! -f "$IDENT_FILE" ]; then
    echo "Error: Identity file not found: $IDENT_FILE" >&2
    exit 1
  fi

  # Read session_id from identity file
  SESSION_ID=$(jq -r '.session_id // ""' "$IDENT_FILE" 2>/dev/null || echo "")
  HEARTBEAT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  # Update identity file with listener heartbeat using jq for safe JSON manipulation
  jq --arg agent_id "$AGENT_ID" \
     --arg session_id "$SESSION_ID" \
     --arg heartbeat "$HEARTBEAT" \
     '.listener = {agent_id: $agent_id, session_id: $session_id, heartbeat: $heartbeat}' \
     "$IDENT_FILE" > "${IDENT_FILE}.tmp" && mv "${IDENT_FILE}.tmp" "$IDENT_FILE"

  echo "Listener heartbeat updated: $HEARTBEAT"
  exit 0
fi

# 1. Ensure daemon is running
if ! thrum --repo "$THRUM_HOME" daemon status &>/dev/null; then
  thrum --repo "$THRUM_HOME" daemon start
fi

# 2. Read existing identity from thrum whoami
AGENT_INFO=$(thrum --repo "$THRUM_HOME" whoami --json 2>/dev/null || echo '{}')
AGENT_NAME=$(echo "$AGENT_INFO" | jq -r 'select(.agent_id != null) | .agent_id // empty')
AGENT_ROLE=$(echo "$AGENT_INFO" | jq -r 'select(.role != null) | .role // empty')
AGENT_MODULE=$(echo "$AGENT_INFO" | jq -r 'select(.module != null) | .module // empty')
AGENT_INTENT=$(echo "$AGENT_INFO" | jq -r 'select(.intent != null) | .intent // empty')

# If whoami returned nothing, thrum is not initialized in this worktree.
# Allow env var overrides, but don't silently fall back to hardcoded defaults.
if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME="${THRUM_NAME:-}"
  AGENT_ROLE="${THRUM_ROLE:-}"
  AGENT_MODULE="${THRUM_MODULE:-}"
  AGENT_INTENT="${THRUM_INTENT:-}"

  if [ -z "$AGENT_NAME" ]; then
    echo "⚠ Thrum is not initialized in this worktree ($(pwd))."
    echo "  No identity found via 'thrum whoami' and no THRUM_NAME env var set."
    echo "  Run: thrum quickstart --name <name> --role <role> --module <module> --intent <intent>"
    exit 1
  fi
else
  # Allow env vars to override whoami values
  AGENT_NAME="${THRUM_NAME:-$AGENT_NAME}"
  AGENT_ROLE="${THRUM_ROLE:-$AGENT_ROLE}"
  AGENT_MODULE="${THRUM_MODULE:-$AGENT_MODULE}"
  AGENT_INTENT="${THRUM_INTENT:-$AGENT_INTENT}"
fi

export THRUM_NAME="$AGENT_NAME"
export THRUM_AGENT_ID="${THRUM_AGENT_ID:-$AGENT_NAME}"
export THRUM_ROLE="$AGENT_ROLE"
export THRUM_MODULE="$AGENT_MODULE"
export THRUM_INTENT="$AGENT_INTENT"

# Persist env vars into Claude Code's session environment.
# CLAUDE_ENV_FILE is provided by SessionStart hooks — vars written here survive
# into subsequent Bash tool calls. Without this, exports die with the subprocess.
if [ -n "$CLAUDE_ENV_FILE" ]; then
  cat >> "$CLAUDE_ENV_FILE" <<ENVEOF
export THRUM_HOME="$THRUM_HOME"
export THRUM_NAME="$THRUM_NAME"
export THRUM_AGENT_ID="$THRUM_AGENT_ID"
export THRUM_ROLE="$THRUM_ROLE"
export THRUM_MODULE="$THRUM_MODULE"
export THRUM_INTENT="$THRUM_INTENT"
ENVEOF
fi

# 3. Register agent (reuses existing identity)
thrum --repo "$THRUM_HOME" quickstart \
  --name "$AGENT_NAME" \
  --role "$AGENT_ROLE" \
  --module "$AGENT_MODULE" \
  --intent "$AGENT_INTENT" \
  --json

# 4. Check inbox and output context
thrum --repo "$THRUM_HOME" inbox --unread --json

# 5. Optional: Announce presence
if [ "${THRUM_ANNOUNCE:-false}" = "true" ]; then
  thrum --repo "$THRUM_HOME" send "Agent $AGENT_NAME online" --to @everyone --json
fi
