#!/bin/bash
# Universal Thrum agent startup script
# Auto-generated by thrum init
set -e

# 1. Ensure daemon is running
if ! thrum daemon status &>/dev/null; then
  thrum daemon start
fi

# 2. Read existing identity from thrum whoami
AGENT_INFO=$(thrum whoami --json 2>/dev/null || echo '{}')
AGENT_NAME=$(echo "$AGENT_INFO" | jq -r 'select(.agent_id != null) | .agent_id // empty')
AGENT_ROLE=$(echo "$AGENT_INFO" | jq -r 'select(.role != null) | .role // empty')
AGENT_MODULE=$(echo "$AGENT_INFO" | jq -r 'select(.module != null) | .module // empty')
AGENT_INTENT=$(echo "$AGENT_INFO" | jq -r 'select(.intent != null) | .intent // empty')

# If whoami returned nothing, thrum is not initialized in this worktree.
# Allow env var overrides, but don't silently fall back to hardcoded defaults.
if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME="${THRUM_NAME:-}"
  AGENT_ROLE="${THRUM_ROLE:-}"
  AGENT_MODULE="${THRUM_MODULE:-}"
  AGENT_INTENT="${THRUM_INTENT:-}"

  if [ -z "$AGENT_NAME" ]; then
    echo "⚠ Thrum is not initialized in this worktree ($(pwd))."
    echo "  No identity found via 'thrum whoami' and no THRUM_NAME env var set."
    echo "  Run: thrum quickstart --name <name> --role <role> --module <module> --intent <intent>"
    exit 1
  fi
else
  # Allow env vars to override whoami values
  AGENT_NAME="${THRUM_NAME:-$AGENT_NAME}"
  AGENT_ROLE="${THRUM_ROLE:-$AGENT_ROLE}"
  AGENT_MODULE="${THRUM_MODULE:-$AGENT_MODULE}"
  AGENT_INTENT="${THRUM_INTENT:-$AGENT_INTENT}"
fi

# 3. Register agent (reuses existing identity)
thrum quickstart \
  --name "$AGENT_NAME" \
  --role "$AGENT_ROLE" \
  --module "$AGENT_MODULE" \
  --intent "$AGENT_INTENT" \
  --json

# 4. Check inbox and output context
thrum inbox --unread --json

# 5. Optional: Announce presence
if [ "${THRUM_ANNOUNCE:-false}" = "true" ]; then
  thrum send "Agent $AGENT_NAME online" --to @everyone --json
fi
